### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by k0dev** [k0dev/erlang-notes#8]
**TODO**

- [ ] **Appunti sulla gestione degli errori**
- [ ] **Appunti sulla distribution (nodi, lib_chan, ecc)**
- [x] Spiegare string formatting (~p, ~w, ecc.)
- [x] Aggiungere esempi sulle guard
- [x] Spiegare le guard
- [x] Aggiungere esempio "anagrammi" per spiegare meglio le list comprehension
- [x] Spiegare meglio le BIF
